# Generated by Django 6.0.4 on 2026-04-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('especificacao_tecnica', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'materiais',
            },
        ),
    ]
