# Generated by Django 6.0.4 on 2026-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.CharField(default='Genérico', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('nome', 'cor', 'unidade_medida', 'marca'), name='unique_material_item'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_estoque__gte', 0)), name='quantidade_nao_negativa'),
        ),
    ]
